# Generated by Django 2.2.4 on 2019-08-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={},
        ),
    ]
